/*
DELETE FROM xsd.DSETREKVMATEKONK;
DELETE FROM xsd.DSETREKVMATEMIKR;
DELETE FROM xsd.DSETREKVMATEMAKR;
DELETE FROM xsd.DSETREKVMATEDIAG;
DELETE FROM xsd.DSETREKVMATELPRP;
DELETE FROM xsd.DSETREKVMATE;
DELETE FROM xsd.DSETREKVLPRP;
DELETE FROM xsd.DSETREKV;
DELETE FROM xsd.DSET;
*/